module.exports = [{
  "login": "nessieclarke",
  "id": 26820864,
  "type": "User",
  "site_admin": false,
  "firstName": "Vanessa",
  "lastName": "Clarke",
  "company": "WICA",
  "car reg": "WK57 000",
  "make": "Honda",
  "model": "Jazz",
  "colour": "blue",
  "permit": "244",
  "workEmail": "nessieclarke@yahoo.co.uk",
  "workPhone": "07871000000",
  "workSkype": "@nessieclarke"

},
{
  login: "so-wow",
  id: 26820864,
  type: "User",
  "site_admin": false,
  "firstName": "Jess",
  "lastName": "McKenzie",
  "company": "WICA",
  "car reg": "BO55 000",
  "make": "Merc",
  "model": "T4",
  "colour": "Red",
  "permit": "257",
  "workEmail": "jess@lala.com",
  "workPhone": "07555000000",
  "workSkype": "@jessmckenziee"

},
{
  "login": "hannnahrub",
  "id": 26820864,
  "type": "User",
  "site_admin": false,
  "firstName": "hannah",
  "lastName": "rub",
  "company": "WICA",
  "car reg": "SO67 000",
  "make": "KA",
  "model": "Smart",
  "colour": "silver",
  "permit": "300",
  "workEmail": "hannahrub@lala.com",
  "workPhone": "07987000000",
  "workSkype": "@hannahrub"

},
{
  "login": "vanessatsang",
  "id": 26820864,
  "type": "User",
  "site_admin": true,
  "firstName": "Vanessa",
  "lastName": "Tsang",
  "company": "WICA",
  "car reg": "RO64 000",
  "make": "Honda",
  "model": "Jazz",
  "colour": "Red",
  "permit": "100",
  "workEmail": "vanessa@tsang.com",
  "workPhone": "07871000000",
  "workSkype": "@vanessatsang"

}];